apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
  namespace: kustomize-demo
  labels:
    app: streamlit-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: stream-lit-app
        image: rajesh17mca/streamlit-app-demo:latest
        resources:
          request:
            cpu: "0.5"
            memory: "500M"
          limits:
            cpu: "1"
            memory: "1Gi"
        