apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deployment-patch
  namespace: kustomize-demo
spec:
  patches:
    - target:
        kind: Deployment
        name: streamlit-app-deployment
        namespace: kustomize-demo
      patch: |-
        - op: add
          path: /spec/template/metadata/labels
          value: "tag-name: patch"
      
  prune: true
  timeout: 1m
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: kustomize-app-demo

